#!/usr/bin/env bash
#
# Setup script for Roe editor - downloads Julia and configures the build environment
#
set -euo pipefail

JULIA_VERSION="1.11.2"
JULIA_MINOR="1.11"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JULIA_DIR="$PROJECT_ROOT/julia"

# Detect platform
detect_platform() {
    local os arch
    os="$(uname -s)"
    arch="$(uname -m)"

    case "$os" in
        Linux)
            case "$arch" in
                x86_64)  echo "linux-x86_64" ;;
                aarch64) echo "linux-aarch64" ;;
                *)       echo "Unsupported architecture: $arch" >&2; exit 1 ;;
            esac
            ;;
        Darwin)
            case "$arch" in
                x86_64)  echo "mac-x86_64" ;;
                arm64)   echo "mac-aarch64" ;;
                *)       echo "Unsupported architecture: $arch" >&2; exit 1 ;;
            esac
            ;;
        *)
            echo "Unsupported OS: $os" >&2
            exit 1
            ;;
    esac
}

# Get download URL for platform
get_download_url() {
    local platform="$1"
    local base_url="https://julialang-s3.julialang.org/bin"

    case "$platform" in
        linux-x86_64)
            echo "$base_url/linux/x64/$JULIA_MINOR/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
            ;;
        linux-aarch64)
            echo "$base_url/linux/aarch64/$JULIA_MINOR/julia-$JULIA_VERSION-linux-aarch64.tar.gz"
            ;;
        mac-x86_64)
            echo "$base_url/mac/x64/$JULIA_MINOR/julia-$JULIA_VERSION-mac64.tar.gz"
            ;;
        mac-aarch64)
            echo "$base_url/mac/aarch64/$JULIA_MINOR/julia-$JULIA_VERSION-macaarch64.tar.gz"
            ;;
    esac
}

# Check if Julia is already set up
check_existing() {
    if [[ -x "$JULIA_DIR/bin/julia" ]]; then
        local version
        version=$("$JULIA_DIR/bin/julia" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || true)
        if [[ "$version" == "$JULIA_VERSION" ]]; then
            echo "Julia $JULIA_VERSION is already installed at $JULIA_DIR"
            return 0
        fi
    fi
    return 1
}

# Download and extract Julia
download_julia() {
    local platform url archive_name
    platform=$(detect_platform)
    url=$(get_download_url "$platform")
    archive_name="julia-$JULIA_VERSION.tar.gz"

    echo "Detected platform: $platform"
    echo "Downloading Julia $JULIA_VERSION..."
    echo "URL: $url"

    # Create temp directory for download
    local tmp_dir
    tmp_dir=$(mktemp -d)
    trap "rm -rf '$tmp_dir'" EXIT

    # Download
    if command -v curl &>/dev/null; then
        curl -fSL "$url" -o "$tmp_dir/$archive_name"
    elif command -v wget &>/dev/null; then
        wget -q "$url" -O "$tmp_dir/$archive_name"
    else
        echo "Error: Neither curl nor wget found" >&2
        exit 1
    fi

    echo "Extracting..."

    # Remove existing julia directory if present
    rm -rf "$JULIA_DIR"
    mkdir -p "$JULIA_DIR"

    # Extract - Julia archives have a julia-x.y.z directory inside
    tar -xzf "$tmp_dir/$archive_name" -C "$tmp_dir"

    # Move contents from julia-x.y.z to our julia directory
    mv "$tmp_dir/julia-$JULIA_VERSION"/* "$JULIA_DIR/"

    echo "Julia installed to $JULIA_DIR"
}

# Create .cargo/config.toml with environment settings
create_cargo_config() {
    local cargo_dir="$PROJECT_ROOT/.cargo"
    local config_file="$cargo_dir/config.toml"

    mkdir -p "$cargo_dir"

    # Check if config already exists and has our settings
    if [[ -f "$config_file" ]] && grep -q "JLRS_JULIA_DIR" "$config_file"; then
        echo "Cargo config already contains Julia settings"
        return
    fi

    echo "Creating $config_file..."

    # Append or create config
    cat >> "$config_file" << EOF

# Julia configuration for jlrs (auto-generated by setup-julia.sh)
[env]
JULIA_DIR = "$JULIA_DIR"
JLRS_JULIA_DIR = "$JULIA_DIR"

[build]
rustflags = ["-C", "link-arg=-rdynamic"]
EOF

    echo "Cargo config updated"
}

# Install required Julia packages
install_julia_packages() {
    echo ""
    echo "Installing Julia packages..."
    echo ""

    "$JULIA_DIR/bin/julia" --project="$PROJECT_ROOT" -e '
        using Pkg

        # Required packages for Roe
        packages = [
            "JuliaSyntaxHighlighting",  # Syntax highlighting for Julia files
        ]

        for pkg in packages
            println("Installing $pkg...")
            try
                Pkg.add(pkg)
                println("  ✓ $pkg installed")
            catch e
                println("  ✗ Failed to install $pkg: $e")
            end
        end

        println("\nPrecompiling packages...")
        Pkg.precompile()
        println("Done!")
    '
}

# Add julia/lib to a shell config hint
print_runtime_hint() {
    echo ""
    echo "=========================================="
    echo "Setup complete!"
    echo "=========================================="
    echo ""
    echo "To build: cargo build"
    echo ""
    echo "IMPORTANT: At runtime, Julia's library must be findable."
    echo "Add this to your shell profile (~/.bashrc, ~/.zshrc, etc.):"
    echo ""
    echo "  export LD_LIBRARY_PATH=\"$JULIA_DIR/lib:\$LD_LIBRARY_PATH\""
    echo ""
    echo "Or run the editor with:"
    echo ""
    echo "  LD_LIBRARY_PATH=\"$JULIA_DIR/lib\" cargo run"
    echo ""
}

# Main
main() {
    echo "Roe Editor - Julia Setup"
    echo "========================"
    echo ""

    local need_packages=false

    if check_existing; then
        create_cargo_config
    else
        download_julia
        create_cargo_config
        need_packages=true
    fi

    # Install packages if this is a fresh install or if --packages flag is passed
    if [[ "$need_packages" == true ]] || [[ "${1:-}" == "--packages" ]]; then
        install_julia_packages
    fi

    print_runtime_hint
}

main "$@"
